# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
#git token   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

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install
      run: npm  install

    - name: Build
      run: npm run docs

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${secrets.BT_TOOLS}
        BRANCH: gh-pages
        FOLDER: dist

